src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 150)]
    #[Assert\Length(
        min: 2,
        max: 50,
    )]
    #[Assert\Type(
        'alpha'
    )]
    private $Nom;

    #[ORM\Column(type: 'float')]
    private $Prix;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Prix')
            ->add("submit",SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ExamController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
#[Route('/exam')]
class ExamController extends AbstractController
{
    #[Route('/acc', name: 'acc_exam')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $repositery=$doctrine->getRepository(Article::class);
        $a= $repositery->findBy([],['id'=>'DESC']);
        return $this->render('exam/index.html.twig',[
            'article'=>$a
        ]);
    }
    #[Route('/detail/{id}', name: 'detail_exam')]
    public function detail(ManagerRegistry $doctrine,Article $article): Response
    {
        return $this->render('exam/detail.html.twig',[
            'article'=>$article
        ]);
    }
    #[Route('/supp/{id}', name: 'del_exam')]
    public function DeleteArticle(ManagerRegistry $doctrine,Article $article=null): RedirectResponse
    {
        if($article){
            $Manager=$doctrine->getManager();
            $Manager->remove($article);
            $Manager->flush();
            $this->addFlash('success',"article supprimer avec success");
        }
        else{
            $this->addFlash('error',"tu ne peux pas supp ce id car il n'existe pas");
        }
        return $this->redirectToRoute('acc_exam');

    }
    #[Route('/add', name: 'add_exam')]
    public function addArticle(ManagerRegistry $doctrine,Request $request): Response
    {  $entityManager=$doctrine->getManager();
        $e=new Article();
        $form=$this->createForm(ArticleType::class,$e);
        $form->handleRequest($request);
        if(!$form->isSubmitted()){
            return $this->render('exam/formulaire.html.twig',[
                'form'=>$form->createView(),
            ]);}
        else{
            $entityManager->persist($e);
            $entityManager->flush();
            $this->addFlash('success',$e->getNom().' est ajouté avec success');
            return $this->redirectToRoute('acc_exam');
        }
    }
    #[Route('/edit/{id?0}', name: 'edit_exam')]
    public function add(ManagerRegistry $doctrine,Article $article= null,Request $request): Response
    {  $entityManager=$doctrine->getManager();
        $new=false;
        if(!$article){
            $article=new Article();
            $new=true;
        }
        $form=$this->createForm(ArticleType::class,$article);
        $form->handleRequest($request);

        if(!$form->isSubmitted()){
            return $this->render('exam/formulaire.html.twig',[
                'form'=>$form->createView(),
            ]);}
        else{
            $entityManager->persist($article);
            $entityManager->flush();
            if(!$new){
                $this->addFlash('success',$article->getNom().' est edité avec success');}
            else{$this->addFlash('success',$article->getNom().' est ajouté avec success');}
        }
        return $this->redirectToRoute('acc_exam');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
        <link rel="stylesheet" href="{{asset("bootstrap-5.1.3-dist/css/bootstrap.css") }}">
        <script src="{{ asset('bootstrap-5.1.3-dist/js/bootstrap.bundle.js') }}"></script>
        <script src="{{ asset('bootstrap-5.1.3-dist/js/bootstrap.js') }}"></script>
    </head>
    <body>
    <header class="alert alert-dark">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-3"></div>
            <div class="col-3"></div>
            <div class="col-3">
                <a href="{{ path('acc_exam') }}" class="btn btn-primary">Home</a>
                <a href="{{ path('add_exam') }}" class="btn btn-primary">Ajouter Article</a>
            </div>
        </div>
        {% block body %}{% endblock %}
    </body>
</html>

templates/exam/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="alert alert-success">
    <p>id est :{{ article.id }}</p>
    <p>Nom est :{{ article.nom }}</p>
    <p>Prix est :{{ article.prix }}</p>
</div>
{% endblock %}

{% block title %}

{% endblock %}

templates/exam/formulaire.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{{ form(form) }}
{% endblock %}

{% block title %}

{% endblock %}

templates/exam/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ExamController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

     <table class="table" style="border: 2px black solid">
         <tr style="border: 2px black solid">
             <td style="border: 2px black solid">NOM</td>
             <td style="border: 2px black solid">Prix</td>
             <td style="border: 2px black solid">Actions</td>
         </tr>
         {% for a in article %}
            <tr style="border: 2px black solid">
             <td style="border: 2px black solid">{{ (a.getNom()|upper)|trim }}</td>
             <td style="border: 2px black solid">
                <p> prix en HT :{{ a.getPrix()|number_format(2,'.',',') }}</p>
                <p>prix en TTC:{{ (a.getPrix()*0.81)|number_format(2,'.',',') }}</p>
             </td>
             <td style="border: 2px black solid">
                 <a href="{{ path('detail_exam',{'id':a.id}) }}" class="btn btn-primary">Details</a>
                 <a href="{{ path('edit_exam',{'id':a.id}) }}" class="btn btn-primary">Modifier</a>
                 <a href="{{ path('del_exam',{'id':a.id}) }}" class="btn btn-primary">Delete</a>
             </td>
            </tr>
         {% endfor %}
     </table>
 </header>
{% endblock %}